require("max.plugins")

require("max.general")
require("max.git")
require("max.custom")
require("max.keybinds")
require("max.lsp")
require("max.misc")
require("max.telescope")
require("max.treesitter")
require("max.visual")
require("max.overseer")
require("max.debugger")
